### ISSUE TITLE
Option to lock the bottom bar show/hide and plus button translation animation

### ISSUE THREAD

**Issue by nikhilmaurya10** [mnayef95/Android-Weekly#26]
I think after a while that animation will look weird also might confuse users about the navigation once it's hidden

**Comment by mnayef95** [comment]
@nikhilmaurya10 Do you think we need settings screen for disabling and enabling animations?
Also, we can use this screen for other settings in the future like notifications and dark mode

**Comment by nikhilmaurya10** [comment]
@mnayer95 a settings screen should ideally be the place to manage these behaviours.

**Comment by nikhilmaurya10** [comment]
For now as an easter egg we can use long press on the submit button to toggle auto show/hide of the bottom bar.

**Comment by mnayef95** [comment]
This issue has been closed
